/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UserInterface.WorkAreas.FacultyRole.FacultyRoleWorkResp02;

/**
 *
 * @author Hyungs
 */
public class CourseDetailJPanel extends javax.swing.JPanel {

    /**
     * Creates new form CourseDetailJPanel
     */
    public CourseDetailJPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblCourseTitle = new javax.swing.JLabel();
        lblCourseNumber = new javax.swing.JLabel();
        lblCourseName = new javax.swing.JLabel();
        lblCredits = new javax.swing.JLabel();
        lblDepartment = new javax.swing.JLabel();
        lblLastUpdated = new javax.swing.JLabel();
        txtCourseNumber = new javax.swing.JTextField();
        txtCourseName = new javax.swing.JTextField();
        txtCredits = new javax.swing.JTextField();
        txtDepartment = new javax.swing.JTextField();
        txtSeatCapacity = new javax.swing.JTextField();
        btnCourseBack = new javax.swing.JButton();
        btnCourseUpdate = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblCourseOffer = new javax.swing.JTable();
        btnCourseSave = new javax.swing.JButton();

        lblCourseTitle.setFont(new java.awt.Font("맑은 고딕", 1, 18)); // NOI18N
        lblCourseTitle.setText("Course Detail");

        lblCourseNumber.setText("Course Number:");

        lblCourseName.setText("Course Name:");

        lblCredits.setText("Credits:");

        lblDepartment.setText("Dpartment:");

        lblLastUpdated.setText("Last Updated:");

        btnCourseBack.setText("Back");
        btnCourseBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCourseBackActionPerformed(evt);
            }
        });

        btnCourseUpdate.setText("Update");
        btnCourseUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCourseUpdateActionPerformed(evt);
            }
        });

        tblCourseOffer.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Semester", "Schedule", "Seat Capacity", "Available"
            }
        ));
        jScrollPane1.setViewportView(tblCourseOffer);

        btnCourseSave.setText("Save");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(111, 111, 111)
                .addComponent(btnCourseBack)
                .addGap(168, 168, 168)
                .addComponent(btnCourseUpdate)
                .addGap(150, 150, 150)
                .addComponent(btnCourseSave)
                .addContainerGap(155, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(330, 330, 330)
                                .addComponent(lblCourseTitle))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(242, 242, 242)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lblCourseNumber)
                                        .addGap(66, 66, 66)
                                        .addComponent(txtCourseNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lblCourseName)
                                        .addGap(78, 78, 78)
                                        .addComponent(txtCourseName))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lblCredits)
                                            .addComponent(lblDepartment)
                                            .addComponent(lblLastUpdated))
                                        .addGap(81, 81, 81)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtCredits)
                                            .addComponent(txtDepartment)
                                            .addComponent(txtSeatCapacity, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblCourseTitle)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCourseNumber)
                    .addComponent(txtCourseNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCourseName)
                    .addComponent(txtCourseName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCredits)
                    .addComponent(txtCredits, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDepartment)
                    .addComponent(txtDepartment, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblLastUpdated)
                    .addComponent(txtSeatCapacity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 110, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCourseBack)
                    .addComponent(btnCourseUpdate)
                    .addComponent(btnCourseSave))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnCourseBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCourseBackActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCourseBackActionPerformed

    private void btnCourseUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCourseUpdateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCourseUpdateActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCourseBack;
    private javax.swing.JButton btnCourseSave;
    private javax.swing.JButton btnCourseUpdate;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblCourseName;
    private javax.swing.JLabel lblCourseNumber;
    private javax.swing.JLabel lblCourseTitle;
    private javax.swing.JLabel lblCredits;
    private javax.swing.JLabel lblDepartment;
    private javax.swing.JLabel lblLastUpdated;
    private javax.swing.JTable tblCourseOffer;
    private javax.swing.JTextField txtCourseName;
    private javax.swing.JTextField txtCourseNumber;
    private javax.swing.JTextField txtCredits;
    private javax.swing.JTextField txtDepartment;
    private javax.swing.JTextField txtSeatCapacity;
    // End of variables declaration//GEN-END:variables
}
