/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UserInterface.WorkAreas.StudentRole;

/**
 *
 * @author sumayyahhusain
 */
public class GraduationRequirementsJPanel extends javax.swing.JPanel {

    /**
     * Creates new form GraduationRequirementsJPanel
     */
    public GraduationRequirementsJPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblGradRequirementsTitle = new javax.swing.JLabel();
        btnBack = new javax.swing.JButton();
        lblCredits = new javax.swing.JLabel();
        fieldCredits = new javax.swing.JTextField();
        lblOverallGPA = new javax.swing.JLabel();
        fieldGPA = new javax.swing.JTextField();
        lblGradStatus = new javax.swing.JLabel();
        fieldGradStatus = new javax.swing.JTextField();

        lblGradRequirementsTitle.setFont(new java.awt.Font("Helvetica Neue", 1, 24)); // NOI18N
        lblGradRequirementsTitle.setText("Graduation Requirements & Progress");

        btnBack.setText("<< Back");

        lblCredits.setText("Credits:");

        fieldCredits.setEditable(false);
        fieldCredits.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldCreditsActionPerformed(evt);
            }
        });

        lblOverallGPA.setText("Overall GPA:");

        fieldGPA.setEditable(false);

        lblGradStatus.setText("Graduation Status:");

        fieldGradStatus.setEditable(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(btnBack)
                        .addGap(107, 107, 107)
                        .addComponent(lblGradRequirementsTitle))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(169, 169, 169)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblOverallGPA)
                            .addComponent(lblCredits)
                            .addComponent(lblGradStatus))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(fieldGradStatus, javax.swing.GroupLayout.DEFAULT_SIZE, 203, Short.MAX_VALUE)
                            .addComponent(fieldGPA)
                            .addComponent(fieldCredits))))
                .addContainerGap(213, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblGradRequirementsTitle)
                    .addComponent(btnBack))
                .addGap(95, 95, 95)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCredits)
                    .addComponent(fieldCredits, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblOverallGPA)
                    .addComponent(fieldGPA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblGradStatus)
                    .addComponent(fieldGradStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(236, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void fieldCreditsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldCreditsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldCreditsActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JTextField fieldCredits;
    private javax.swing.JTextField fieldGPA;
    private javax.swing.JTextField fieldGradStatus;
    private javax.swing.JLabel lblCredits;
    private javax.swing.JLabel lblGradRequirementsTitle;
    private javax.swing.JLabel lblGradStatus;
    private javax.swing.JLabel lblOverallGPA;
    // End of variables declaration//GEN-END:variables
}
