/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UserInterface.WorkAreas.StudentRole;

import Business.Business;
import Business.Profiles.StudentProfile;
import javax.swing.JPanel;

/**
 *
 * @author sumayyahhusain
 */
public class StudentCourseWork extends javax.swing.JPanel {

    private StudentProfile studentProfile;
    private JPanel CardSequencePanel;
    Business business;
    
    /**
     * Creates new form StudentCourseWork
     */
    public StudentCourseWork(StudentProfile studentProfile,JPanel CardSequencePanel) {
        this.studentProfile = studentProfile;
        this.CardSequencePanel = CardSequencePanel;
        
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblManageCourseworkTitle = new javax.swing.JLabel();
        btnBack = new javax.swing.JButton();
        tblCurrentCourses = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        lblCurrentSemesterCourses = new javax.swing.JLabel();
        lblUploadAssignment = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        fieldAssignment = new javax.swing.JTextArea();
        btnSubmitAssignment = new javax.swing.JButton();

        lblManageCourseworkTitle.setFont(new java.awt.Font("Helvetica Neue", 1, 24)); // NOI18N
        lblManageCourseworkTitle.setText("Manage Coursework");

        btnBack.setText("<< Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Course ID", "Title", "Credits", "Status"
            }
        ));
        tblCurrentCourses.setViewportView(jTable1);

        lblCurrentSemesterCourses.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        lblCurrentSemesterCourses.setText("Current Semester Courses");

        lblUploadAssignment.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        lblUploadAssignment.setText("Upload an Assignment");

        fieldAssignment.setColumns(20);
        fieldAssignment.setRows(5);
        jScrollPane2.setViewportView(fieldAssignment);

        btnSubmitAssignment.setText("Submit");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnSubmitAssignment)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(lblUploadAssignment)
                        .addComponent(lblCurrentSemesterCourses)
                        .addComponent(tblCurrentCourses, javax.swing.GroupLayout.DEFAULT_SIZE, 791, Short.MAX_VALUE)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(btnBack)
                            .addGap(194, 194, 194)
                            .addComponent(lblManageCourseworkTitle))
                        .addComponent(jScrollPane2)))
                .addContainerGap(34, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnBack)
                    .addComponent(lblManageCourseworkTitle))
                .addGap(28, 28, 28)
                .addComponent(lblCurrentSemesterCourses)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tblCurrentCourses, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43)
                .addComponent(lblUploadAssignment)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnSubmitAssignment)
                .addContainerGap(23, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        CardSequencePanel.removeAll();
        StudentWorkAreaJPanel studentPanel = new StudentWorkAreaJPanel(business, studentProfile, CardSequencePanel);
        CardSequencePanel.add("student", studentPanel);
        ((java.awt.CardLayout) CardSequencePanel.getLayout()).next(CardSequencePanel);
    }//GEN-LAST:event_btnBackActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnSubmitAssignment;
    private javax.swing.JTextArea fieldAssignment;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel lblCurrentSemesterCourses;
    private javax.swing.JLabel lblManageCourseworkTitle;
    private javax.swing.JLabel lblUploadAssignment;
    private javax.swing.JScrollPane tblCurrentCourses;
    // End of variables declaration//GEN-END:variables
}
