/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

 /*
 * WorkAreaJPanel.java
 *
 * Created on May 17, 2020, 8:35:29 AM
 */
package UserInterface.WorkAreas.AdminRole;

import Business.Business;
import UserInterface.WorkAreas.AdminRole.AdministerUserAccountsWorkResp.ManageUserAccountsJPanel;
import UserInterface.WorkAreas.AdminRole.AnalyticsDashboard.AnalyticsDashboardJPanel;
import UserInterface.WorkAreas.AdminRole.AnalyticsDashboard.AnalyticsDashboardJPanel;
import UserInterface.WorkAreas.AdminRole.ManagePersonnelWorkResp.ManagePersonsJPanel;
import UserInterface.WorkAreas.AdminRole.ManageRecords.ManageRecordsJPanel;
import UserInterface.WorkAreas.AdminRole.MyProfile.AdminManageProfileJPanel;
import info5100.university.example.Persona.Person;

import javax.swing.JPanel;

/**
 *
 * @author kal
 */
public class AdminRoleWorkAreaJPanel extends javax.swing.JPanel {

    javax.swing.JPanel CardSequencePanel;
    Business business;
    Person loggedInPerson;

    /**
     * Creates new form UnitRiskWorkArea
     */

    public AdminRoleWorkAreaJPanel(Business b, JPanel clp, Person p) {

        business = b;
        this.CardSequencePanel = clp;
        this.loggedInPerson = p;
        
        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnAdminUserAccount = new javax.swing.JButton();
        btnManageFacultyStudent = new javax.swing.JButton();
        btnRegisterPerson = new javax.swing.JButton();
        btnMyProfile = new javax.swing.JButton();
        btnAnalyticDashboard = new javax.swing.JButton();

        setForeground(new java.awt.Color(51, 51, 51));

        btnAdminUserAccount.setBackground(new java.awt.Color(102, 153, 255));
        btnAdminUserAccount.setFont(getFont());
        btnAdminUserAccount.setForeground(new java.awt.Color(255, 255, 255));
        btnAdminUserAccount.setText("Administer User Accounts");
        btnAdminUserAccount.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnAdminUserAccount.setMaximumSize(new java.awt.Dimension(200, 40));
        btnAdminUserAccount.setMinimumSize(new java.awt.Dimension(20, 23));
        btnAdminUserAccount.setPreferredSize(new java.awt.Dimension(240, 30));
        btnAdminUserAccount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdminUserAccountIdentifyResourceAssetsActionPerformed(evt);
            }
        });

        btnManageFacultyStudent.setBackground(new java.awt.Color(102, 153, 255));
        btnManageFacultyStudent.setFont(getFont());
        btnManageFacultyStudent.setForeground(new java.awt.Color(255, 255, 255));
        btnManageFacultyStudent.setText("Manage Faculty&Student");
        btnManageFacultyStudent.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnManageFacultyStudent.setMaximumSize(new java.awt.Dimension(200, 40));
        btnManageFacultyStudent.setMinimumSize(new java.awt.Dimension(20, 20));
        btnManageFacultyStudent.setPreferredSize(new java.awt.Dimension(240, 25));
        btnManageFacultyStudent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManageFacultyStudentActionPerformed(evt);
            }
        });

        btnRegisterPerson.setBackground(new java.awt.Color(102, 153, 255));
        btnRegisterPerson.setFont(getFont());
        btnRegisterPerson.setForeground(new java.awt.Color(255, 255, 255));
        btnRegisterPerson.setText("Register  Persons (HR)");
        btnRegisterPerson.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnRegisterPerson.setMaximumSize(new java.awt.Dimension(200, 40));
        btnRegisterPerson.setMinimumSize(new java.awt.Dimension(20, 20));
        btnRegisterPerson.setPreferredSize(new java.awt.Dimension(240, 25));
        btnRegisterPerson.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegisterPersonActionPerformed(evt);
            }
        });

        btnMyProfile.setBackground(new java.awt.Color(102, 153, 255));
        btnMyProfile.setFont(getFont());
        btnMyProfile.setForeground(new java.awt.Color(255, 255, 255));
        btnMyProfile.setText("My Profile");
        btnMyProfile.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnMyProfile.setMaximumSize(new java.awt.Dimension(145, 40));
        btnMyProfile.setMinimumSize(new java.awt.Dimension(20, 20));
        btnMyProfile.setPreferredSize(new java.awt.Dimension(240, 25));
        btnMyProfile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMyProfileIdentifyEventsActionPerformed(evt);
            }
        });

        btnAnalyticDashboard.setBackground(new java.awt.Color(102, 153, 255));
        btnAnalyticDashboard.setFont(getFont());
        btnAnalyticDashboard.setForeground(new java.awt.Color(255, 255, 255));
        btnAnalyticDashboard.setText("Analytics Dashboard");
        btnAnalyticDashboard.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnAnalyticDashboard.setMaximumSize(new java.awt.Dimension(200, 40));
        btnAnalyticDashboard.setMinimumSize(new java.awt.Dimension(20, 20));
        btnAnalyticDashboard.setPreferredSize(new java.awt.Dimension(240, 25));
        btnAnalyticDashboard.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAnalyticDashboardActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(101, 101, 101)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnMyProfile, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnManageFacultyStudent, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnAdminUserAccount, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(75, 75, 75)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnRegisterPerson, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnAnalyticDashboard, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(632, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(117, 117, 117)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnRegisterPerson, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAdminUserAccount, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(54, 54, 54)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnManageFacultyStudent, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAnalyticDashboard, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(54, 54, 54)
                .addComponent(btnMyProfile, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(127, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnAdminUserAccountIdentifyResourceAssetsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdminUserAccountIdentifyResourceAssetsActionPerformed
        // TODO add your handling code here:

        ManageUserAccountsJPanel aos = new ManageUserAccountsJPanel(business, CardSequencePanel);

        CardSequencePanel.add("ManageVulns", aos);
        ((java.awt.CardLayout) CardSequencePanel.getLayout()).next(CardSequencePanel);

    }//GEN-LAST:event_btnAdminUserAccountIdentifyResourceAssetsActionPerformed

    private void btnRegisterPersonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegisterPersonActionPerformed
        // TODO add your handling code here:

        ManagePersonsJPanel aos = new ManagePersonsJPanel(business, CardSequencePanel);

        CardSequencePanel.add("Manage Persons", aos);
        ((java.awt.CardLayout) CardSequencePanel.getLayout()).next(CardSequencePanel);

    }//GEN-LAST:event_btnRegisterPersonActionPerformed

    private void btnAnalyticDashboardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAnalyticDashboardActionPerformed
        // TODO add your handling code here:
        AnalyticsDashboardJPanel analyticsPanel = new AnalyticsDashboardJPanel(business, CardSequencePanel);
        CardSequencePanel.add("AnalyticsDashboard", analyticsPanel);
        ((java.awt.CardLayout) CardSequencePanel.getLayout()).next(CardSequencePanel);
    }//GEN-LAST:event_btnAnalyticDashboardActionPerformed

    private void btnMyProfileIdentifyEventsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMyProfileIdentifyEventsActionPerformed
        if (loggedInPerson != null) {
            AdminManageProfileJPanel adminProfilePanel = new AdminManageProfileJPanel(CardSequencePanel, loggedInPerson);
            CardSequencePanel.add("AdminProfilePanel", adminProfilePanel);
            ((java.awt.CardLayout) CardSequencePanel.getLayout()).next(CardSequencePanel);
        } else {
            // This should ideally not happen if login logic is correct
            javax.swing.JOptionPane.showMessageDialog(this, "Error: Logged in user information not found.", "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnMyProfileIdentifyEventsActionPerformed

    private void btnManageFacultyStudentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManageFacultyStudentActionPerformed
        ManageRecordsJPanel manageRecordsPanel = new ManageRecordsJPanel(business, CardSequencePanel);
        CardSequencePanel.add("ManageRecordsPanel", manageRecordsPanel);
        ((java.awt.CardLayout) CardSequencePanel.getLayout()).next(CardSequencePanel);
    }//GEN-LAST:event_btnManageFacultyStudentActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdminUserAccount;
    private javax.swing.JButton btnAnalyticDashboard;
    private javax.swing.JButton btnManageFacultyStudent;
    private javax.swing.JButton btnMyProfile;
    private javax.swing.JButton btnRegisterPerson;
    // End of variables declaration//GEN-END:variables

}
