/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UserInterface.WorkAreas.FacultyRole.FacultyRoleWorkResp02;

import Business.Business;
import Business.UserAccounts.UserAccount;
import info5100.university.example.CourseSchedule.CourseLoad;
import info5100.university.example.CourseSchedule.CourseOffer;
import info5100.university.example.CourseSchedule.CourseSchedule;
import info5100.university.example.CourseSchedule.Seat;
import info5100.university.example.CourseSchedule.SeatAssignment;
import info5100.university.example.Department.Department;
import info5100.university.example.Persona.Faculty.FacultyAssignment;
import info5100.university.example.Persona.Faculty.FacultyProfile;
import info5100.university.example.Persona.Person;
import info5100.university.example.Persona.StudentProfile;
import java.awt.CardLayout;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Hyungs
 */
public class ManageStudentProfileListJPanel extends javax.swing.JPanel {
    
    Business business;   
    FacultyProfile facultyProfile;
    JPanel CardSequencePanel;
    
    
    
    /**
     * Creates new form ManageStudentProfileListJPanel
     */
    public ManageStudentProfileListJPanel(Business business, FacultyProfile facultyProfile,JPanel CardSequencePanel) {
        initComponents();
        
        this.business = business;
        this.facultyProfile = facultyProfile;
        this.CardSequencePanel = CardSequencePanel;
        
        populateTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitle = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblManageStudentProfile = new javax.swing.JTable();
        btnBack = new javax.swing.JButton();
        btnViewDetails = new javax.swing.JButton();

        lblTitle.setFont(new java.awt.Font("맑은 고딕", 1, 18)); // NOI18N
        lblTitle.setText("Manage Student Profile");

        tblManageStudentProfile.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "NUID", "First Name", "Last Name", "Department", "GPA"
            }
        ));
        jScrollPane1.setViewportView(tblManageStudentProfile);

        btnBack.setText("Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        btnViewDetails.setText("View Details");
        btnViewDetails.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewDetailsActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(302, Short.MAX_VALUE)
                .addComponent(lblTitle)
                .addGap(294, 294, 294))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnBack)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnViewDetails)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTitle)
                .addGap(52, 52, 52)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnBack)
                    .addComponent(btnViewDetails))
                .addContainerGap(236, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnViewDetailsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewDetailsActionPerformed
        // TODO add your handling code here:
        int selectedRow = tblManageStudentProfile.getSelectedRow();
        if (selectedRow < 0) {
            JOptionPane.showMessageDialog(null, "Please select a row.", "Warning", JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        DefaultTableModel model = (DefaultTableModel) tblManageStudentProfile.getModel();
        StudentProfile selectedStudent = (StudentProfile) model.getValueAt(selectedRow, 0);
        
        StudentProfileDetailJPanel sdj = new StudentProfileDetailJPanel(business, CardSequencePanel);
        CardSequencePanel.add("StudentDetail",sdj);
        
        CardLayout layout = (CardLayout)CardSequencePanel.getLayout();
        layout.show(CardSequencePanel, "StudentDetail");
        
        
    }//GEN-LAST:event_btnViewDetailsActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        CardLayout layout = (CardLayout) CardSequencePanel.getLayout();
        layout.show(CardSequencePanel, "faculty");
        
        CardSequencePanel.remove(this);
    }//GEN-LAST:event_btnBackActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnViewDetails;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JTable tblManageStudentProfile;
    // End of variables declaration//GEN-END:variables

    private void populateTable() {
        DefaultTableModel model = (DefaultTableModel) tblManageStudentProfile.getModel();
        model.setRowCount(0);
        
        Department dept = business.getDepartment();
        if (dept == null || facultyProfile == null) return;
        
        String sem = "Spring 2026";
        CourseSchedule cs = dept.getCourseSchedule(sem);
        if (cs == null) return;
        
        java.util.HashSet<StudentProfile> unique = new java.util.HashSet<>();
        
        for (CourseOffer co : cs.getSchedule()) {
            
            FacultyProfile assigned = co.getFacultyProfile();
            if (assigned == null) continue;
            
            //subjects that assigned only
            if (assigned != facultyProfile) continue;
            
            //students enrolled subjects
            for (Seat s : co.getSeatList()) {
                SeatAssignment sa = s.getSeatAssignment();
                if (sa == null) continue;
                
                CourseLoad cl = sa.getCourseLoad();
                if (cl == null) continue;
                
                StudentProfile sp = cl.getStudentProfile();
                if (sp == null) continue;
                
                unique.add(sp);
            }
        }
        for (StudentProfile sp : unique) {
            Object [] row = new Object[5];
            row[0] = sp.getPerson().getPersonId();
            row[1] = sp.getPerson().getFirstName();
            row[2] = sp.getPerson().getLastName();
            row[3] = sp.getDepartment();
            row[4] = sp.getPerson().getGPA();
            
            model.addRow(row);
        }     
    }
}
