/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UserInterface.WorkAreas.AdminRole.AdministerUserAccountsWorkResp;

import Business.Business;
import Business.UserAccounts.UserAccount;
import Business.UserAccounts.UserAccountDirectory;
import info5100.university.example.Persona.Person;
import java.awt.CardLayout;
import java.awt.Component;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author hdIV
 */
public class ManageUserAccountsJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ManageUserAccountsJPanel
     */
    JPanel CardSequencePanel;
    Business business;
    UserAccount selectedUserAccount;
    
    public ManageUserAccountsJPanel(Business bz, JPanel jp) {
        CardSequencePanel = jp;
        this.business = bz;
        initComponents();
        refreshTable();
        
        userTable.getSelectionModel().addListSelectionListener(e -> {
            if (!e.getValueIsAdjusting()) {
                int selectedRow = userTable.getSelectedRow();
                if (selectedRow >= 0) {
                    DefaultTableModel mdl = (DefaultTableModel) userTable.getModel();
                    int modelRow = userTable.convertRowIndexToModel(selectedRow);
                    selectedUserAccount = (UserAccount) mdl.getValueAt(modelRow, 0);
                } else {
                    selectedUserAccount = null;
                }
            }
        });
    
        
    }
    
    public void refreshTable() {
        DefaultTableModel model = (DefaultTableModel) userTable.getModel();
    model.setColumnIdentifiers(new String[]{"User Account", "Username", "Person Name", "Person ID", "Role"});
    model.setRowCount(0);

    UserAccountDirectory uad = business.getUserAccountDirectory();
    for (UserAccount ua : uad.getUserAccountList()) {
        Person person = ua.getAssociatedPerson();
        Object[] row = new Object[5];
        row[0] = ua;
        row[1] = ua.getUserLoginName();
        row[2] = (person != null) ? person.getFirstName() : "N/A";
        row[3] = (person != null) ? person.getPersonId() : "N/A";
        row[4] = ua.getRole();
        model.addRow(row);
    }
        // Hide the first column (User Account Object)
        if (userTable.getColumnModel().getColumnCount() == 5) {
        userTable.removeColumn(userTable.getColumnModel().getColumn(0));
        }
        selectedUserAccount = null; // Reset selection
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitle = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        userTable = new javax.swing.JTable();
        btnCreate = new javax.swing.JButton();
        btnViewEdit = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();

        setBackground(new java.awt.Color(0, 153, 153));
        setLayout(null);

        lblTitle.setFont(new java.awt.Font("Helvetica Neue", 0, 36)); // NOI18N
        lblTitle.setText("Manage User Accounts");
        add(lblTitle);
        lblTitle.setBounds(139, 21, 375, 44);

        jLabel1.setText("User Accounts");
        add(jLabel1);
        jLabel1.setBounds(40, 83, 85, 17);

        userTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "User Name", "Name", "ID", "Role"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, true, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(userTable);
        if (userTable.getColumnModel().getColumnCount() > 0) {
            userTable.getColumnModel().getColumn(0).setResizable(false);
            userTable.getColumnModel().getColumn(1).setResizable(false);
            userTable.getColumnModel().getColumn(2).setResizable(false);
            userTable.getColumnModel().getColumn(3).setResizable(false);
        }

        add(jScrollPane1);
        jScrollPane1.setBounds(40, 118, 577, 265);

        btnCreate.setText("Create");
        btnCreate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateActionPerformed(evt);
            }
        });
        add(btnCreate);
        btnCreate.setBounds(40, 401, 120, 23);

        btnViewEdit.setText("View/Edit");
        btnViewEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewEditActionPerformed(evt);
            }
        });
        add(btnViewEdit);
        btnViewEdit.setBounds(272, 401, 120, 23);

        btnDelete.setText("Delete");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });
        add(btnDelete);
        btnDelete.setBounds(497, 401, 120, 23);

        btnBack.setText("<<Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        add(btnBack);
        btnBack.setBounds(40, 453, 120, 23);
    }// </editor-fold>//GEN-END:initComponents

    private void btnCreateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateActionPerformed
        // TODO add your handling code here:
        AdminUserAccount addUserAccountPanel = new AdminUserAccount(business, CardSequencePanel, null); // Pass business object
        CardSequencePanel.add("AddUserAccount", addUserAccountPanel);
        ((CardLayout) CardSequencePanel.getLayout()).next(CardSequencePanel);
    }//GEN-LAST:event_btnCreateActionPerformed

    private void btnViewEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewEditActionPerformed
        // TODO add your handling code here:
        if (selectedUserAccount == null) {
            JOptionPane.showMessageDialog(this, "Please select a user account from the table first.", "Selection Required", JOptionPane.WARNING_MESSAGE);
            return;
        }
      
        AdminUserAccount editUserAccountPanel = new AdminUserAccount(business, CardSequencePanel, selectedUserAccount); 
        CardSequencePanel.add("EditUserAccount_" + selectedUserAccount.getUserLoginName(), editUserAccountPanel);
        ((CardLayout) CardSequencePanel.getLayout()).next(CardSequencePanel);
    }//GEN-LAST:event_btnViewEditActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        // TODO add your handling code here:
        if (selectedUserAccount == null) {
            JOptionPane.showMessageDialog(this, "Please select a user account from the table to delete.", "Selection Required", JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        //this will prevent the deletion of the admin user account
        if ("admin".equalsIgnoreCase(selectedUserAccount.getUserLoginName())) {
             JOptionPane.showMessageDialog(this, "The default 'admin' account cannot be deleted.", "Deletion Denied", JOptionPane.ERROR_MESSAGE);
             return;
         }
        
        int confirmation = JOptionPane.showConfirmDialog(this,
                "Are you sure you want to delete the user account '" + selectedUserAccount.getUserLoginName() + "'?\nThis action cannot be undone.",
                "Confirm Deletion", JOptionPane.YES_NO_OPTION, JOptionPane.WARNING_MESSAGE);

        if (confirmation == JOptionPane.YES_OPTION) {
            UserAccountDirectory uad = business.getUserAccountDirectory();
            
            boolean removed = uad.getUserAccountList().remove(selectedUserAccount);
            
            if (removed) {
                JOptionPane.showMessageDialog(this, "User account deleted successfully.", "Deletion Success", JOptionPane.INFORMATION_MESSAGE);
                refreshTable();
                
                } else {
                 JOptionPane.showMessageDialog(this, "Failed to delete user account.", "Deletion Error", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        CardSequencePanel.remove(this);
        ((CardLayout) CardSequencePanel.getLayout()).previous(CardSequencePanel);
        
        Component previousComponent = CardSequencePanel.getComponent(CardSequencePanel.getComponentCount() - 1);
    }//GEN-LAST:event_btnBackActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnCreate;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnViewEdit;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JTable userTable;
    // End of variables declaration//GEN-END:variables


}